env: 'LunarLanderContinuous-v3'
connector: 'wm2.env.LunarLander_v3:LunarLanderConnector'
seed_episodes: 5
collect_interval: 10
batch_size: 40
horizon: 64
discount: 0.99
lam: 0.95
exploration_noise: 0.25

dynamics:
  lr: 1e-3
  layers: 1
  hidden_dim: 512

value:
  lr: 1e-3
  hidden_dims: [128]
  nonlin: 'nn.ELU'

policy:
  lr: 2e-3
  hidden_dims: [128]
  nonlin: 'nn.ELU'

reward:
  learnable: False

pcont:
  fixed_length: True
  lr: 1e-3
  hidden_dims: [128]
  nonlin: 'nn.ELU'
  terminal_repeats: 0

viz:
  cooldown: 0
  render_cooldown: 20