env: 'LunarLanderContinuous-v3'
connector: 'wm2.connectors.LunarLander_v3:LunarLanderODEConnector'
seed_episodes: 5
collect_interval: 10
batch_size: 40
horizon: 64
discount: 0.99
lam: 0.95
exploration_noise: 0.25

dynamics:
  lr: 1e-4
  hidden_dim: 128
  ode_method: 'rk4'

value:
  lr: 1e-3
  hidden_dims: [128]
  nonlin: 'nn.ELU'

policy:
  lr: 2e-3
  hidden_dims: [128]
  nonlin: 'nn.ELU'
  clip: 0.1

reward:
  learnable: False

pcont:
  fixed_length: True
  lr: 1e-3
  hidden_dims: [128]
  nonlin: 'nn.ELU'
  terminal_repeats: 0

viz:
  cooldown: 0
  render_cooldown: 20